### ISSUE TITLE
Verify -> Reject leaves the solve in the verify queue

### ISSUE THREAD

**Issue by rexkix** [samfundev/KTANE-Bombs#1]
I entered a solve.  I hit Verify and rejected it.  It was removed from the screen, but when I clicked Verify again, it was there again.

**Comment by rexkix** [comment]
If I reject a solve, it is still removed from the screen, but if I don't change pages and stay on the Verify page and then click on the Verify button, it appears again.  If I were to accept it, the solve doesn't appear.  It *has* been rejected.

If I go to a different page or refresh that page and hit Verify, then everything works as it should.

Suggestion: If I'm on the Verify page and click on the Verify button, force a refresh on the page.

**Comment by Luminoscity** [comment]
Now fixed and will be merged with the switchover.
