### ISSUE TITLE
Be able to see mission description in verify/bomb page

### ISSUE THREAD

**Issue by BlvdBroken** [samfundev/KTANE-Bombs#101]
This would allow verifiers to see relevant modsettings, which would otherwise make some bomb unviable.

**Comment by Luminoscity** [comment]
What is an example of a "mission description"?

**Comment by BlvdBroken** [comment]
![image](https://github.com/samfundev/KTANE-Bombs/assets/38589000/c3ccdbc3-efd7-4b0e-b127-a92ebce718e8)
These modsettings in the description change things about the modules on the bomb.

**Comment by Luminoscity** [comment]
I see. So this is a new field entirely. You want uploaders to be able to type any text they want as the Mission Description when uploading? And we'll find a place to put that on the mission page I suppose.

**Comment by BlvdBroken** [comment]
Would it be possible for the uploaded log to automatically show the mission description?

**Comment by Luminoscity** [comment]
Is that information in the logfile? Can you show me where if so?

**Comment by Luminoscity** [comment]
@BlvdBroken Any more thoughts on this? Sounds like this info doesn't exist in a logfile. So if you want this feature, people are going to have to be able to fill in their own description at upload. And if you don't want that, I'll just close this issue.

**Comment by Luminoscity** [comment]
Notes on a mission page I think covers this.
