### ISSUE TITLE
Multiple static bombs have incorrect time calculation

### ISSUE THREAD

**Issue by BlvdBroken** [samfundev/KTANE-Bombs#102]
![image](https://github.com/samfundev/KTANE-Bombs/assets/38589000/64fff6cf-3a07-4018-a769-1d9e36a2d1b8)
This bomb has multiple 30 minute/1 hour bombs that are incorrectly added together for the total time.

**Comment by Luminoscity** [comment]
This is not a bug. This is a setting. Specifically the Time Mode and Strike Mode setting for a mission. I'll ask for a list of which ones are wrong in our server so we can fix them.
