### ISSUE TITLE
Small solve verified pop-up

### ISSUE THREAD

**Issue by Cirax856** [samfundev/KTANE-Bombs#103]
# Suggestion
## Simple, yet cool idea

When your solve gets verified and you enter the website, you get a small green pop-up at the bottom of the screen that the solve has been verified in the format of "**Congratulations! Your solve of *{bombName}* (*{type}*) with *{team}***", where bombName is the name of the bomb, type is whether you defused it, experted it or EFMed it and team is a list of the team you solve the bomb with.

**Comment by Luminoscity** [comment]
@Cirax856 Difficult to do (currently impossible) since there is no info in the database about when a solve was verified. What about instead a way to list your solves on your user page in order of newest added to the site?

**Comment by Cirax856** [comment]
I believe sort by newest is kind of useless.

What about storing an array for the user of loaded solves and an array of all solves. If the arrays don't match, show the pop-up (this can also get the info about the solve) and update the array. That would be my first guess, which looks possible to do. Again, I haven't looked at the code, so prove me wrong if it isn't.
Thanks for checking out the idea!

**Comment by Luminoscity** [comment]
It's basically the same thing. If you want to find out if your solve was verified, check your use page and sort by Newest, if you see it there, it was verified.
Yeah the problem with your solution is that it would be a database change for only this feature to use. We'd have to store for all solves info about whether the user has seen the popup or not. That's not really what the database is for.
We might be able to do something based on localStorage, but it would only work on the same browser on the same computer as you uploaded the solve.

**Comment by Cirax856** [comment]
Oh I see.
I guess that is no problem. Thanks again.
