### ISSUE TITLE
Filter - Filter mission list by profiles

### ISSUE THREAD

**Issue by rexkix** [samfundev/KTANE-Bombs#18]
Allow the user to filter the mission list by profiles.  These could be Expert or Defuser profiles.  There could be multiple profiles.
If a mission is completely covered by the profiles, it would be listed at the top.
After these missions, missions would be listed that have some modules without coverage in order of the number of modules that aren't covered.  If you open up those missions, "uncovered" modules would have some visual identifier indicating the lack of coverage.

This could be used to help find missions that a team is capable of solving.

**Comment by Luminoscity** [comment]
This is the big one, this one is going to take a lot of small gradual changes. 
I'm thinking starting with it just showing all missions that have **only** modules that you have enabled.
Then adding more complex features like "how many more modules per bomb that I don't know are allowed in the filtered results?"

**Comment by Luminoscity** [comment]
Yay!
![image](https://user-images.githubusercontent.com/10985005/192148682-4c137aab-f4e4-4d15-a73a-2d31fcd8fb54.png)
