### ISSUE TITLE
Support name changes for experts / defusers / mission creators

### ISSUE THREAD

**Issue by rexkix** [samfundev/KTANE-Bombs#21]
Sometimes people change their name.  It'd be nice if the application would support such changes.

"Change all instances of [name] to [new-name]".

**Comment by rexkix** [comment]
Give a warning if the new name is the same as an existing name.

**Comment by samfundev** [comment]
I've implemented renaming, but I didn't implement the warning. Let me know if there's anything wrong with the renaming.
