### ISSUE TITLE
Backup the data automatically

### ISSUE THREAD

**Issue by rexkix** [samfundev/KTANE-Bombs#24]
Backup the data regularly.
Keep multiple revisions so that valuable data isn't lost forever just because a more recent backup (that also doesn't have the data) overwrites the revision that does.

**Comment by Luminoscity** [comment]
The current way we think we will implement this:

- Create an endpoint similar to /json/missiondata that exports **everything** in the database, including IDs and user information. It would be permission locked and only Sam would really need access to it.
- Create a scheduled task that automatically exports the contents of that endpoint to a json file.
    - Create private bitbucket account that stores the bombs.json file containing all database info. 
    - The scheduled task would commit and push the changed to the json file to that repo
    - The repo is private because it contains private user data

**Comment by samfundev** [comment]
I've set up a daily backup of the Postgres database using the pg_dumpall command.
