### ISSUE TITLE
Upload screen - Mouse is I-bar when hovering over the text of the 3 tabs

### ISSUE THREAD

**Issue by rexkix** [samfundev/KTANE-Bombs#36]
This is a trivial bug.  Hell, it may not even be a bug.

On the Upload screen, when I hover my mouse over the three tabs (Solve, Mission, Mission Pack), the cursor is an I-bar when over the text of the button and a pointer when not.  It should be a pointer when it's over any part of those three tabs.

**Comment by Luminoscity** [comment]
Done
