### ISSUE TITLE
Filter - Boss Modules

### ISSUE THREAD

**Issue by samfundev** [samfundev/KTANE-Bombs#38]

**Comment by rexkix** [comment]
Is this addressed by issue #19:

**Comment by samfundev** [comment]
The original request was: (emphasis mine)
> I don't know how difficult this is to implement, but I imagine that it could solve many of the feature suggestions in one fell swoop if you enable it to search for modules, bomb names, solver/creator names, and perhaps a few unique terms such as **"boss modules"**, etc.

I don't believe that is covered by #19. The idea being that you can search for missions that have any boss module.
