### ISSUE TITLE
A User's Page - Since it's a also a list of bombs, allow all the Filter abilities we plan to add to the Home page to it

### ISSUE THREAD

**Issue by rexkix** [samfundev/KTANE-Bombs#43]
For each user's page, allow all the Filter abilities we plan to add to the Home page to it.  

I could see users wanting to know which bombs they did with a particular user.  Or which bombs they did that had FMN on it.
Not listed as an existing filter request, but it'd be nice to see only the EFMs or ones they did as a Defuser.  Etc.

**Comment by Luminoscity** [comment]
Is already possible
![image](https://user-images.githubusercontent.com/10985005/211972641-fac6a15e-65fd-4924-9ff7-421433f7d841.png)
