### ISSUE TITLE
Users - List both a user's Discord name and Solver name

### ISSUE THREAD

**Issue by rexkix** [samfundev/KTANE-Bombs#45]
There are many users who have solver names different from their Discord username.
You can change their name on the Users page to their solver name and the two are now merged/linked.  Great.
But then you can't see the Discord name.  What if you wanted to send them a Discord message?

Why not list both on the Users page?  I suppose then the "Edit Name" button becomes an "Edit Solver Name" button.
Is this a good thing?  I don't even know.  It's certainly not very important.

**Comment by Luminoscity** [comment]
Done and will be merged with the switchover. Only user's with permission to RenameUser may see the discord names however. All other users will see only the solver names, AKA the sheet names.
