### ISSUE TITLE
Challenge bomb uncreachable.

### ISSUE THREAD

**Issue by stuff32** [samfundev/KTANE-Bombs#55]
The challenge bomb of hon'/ is unreachable on the website, it displays a 404 page not found error. The URL interprets the slash in the name as part of the URL and therefore doesnt include it.

**Comment by Luminoscity** [comment]
This issue has already been fixed and will be pushed to the website when the switchover happens.

**Comment by Luminoscity** [comment]
Bug is back, working on it.

**Comment by Luminoscity** [comment]
Fixed
