### ISSUE TITLE
Login and Upload - Same name, different upper/lower case is the same solver name

### ISSUE THREAD

**Issue by rexkix** [samfundev/KTANE-Bombs#57]
1. Disallow two solvers from having the same name with different case on the letters in the name.
2. If an upload includes a solver has a case-insensitive match with an existing solver, then use that solver name.

This way we won't have solves credited to two solver names like: "Rexkix" and "rexkix".

**Comment by Luminoscity** [comment]
Please add these details to the existing issue #29
