### ISSUE TITLE
Users - "Avatar" shows up when profile picture can't be found

### ISSUE THREAD

**Issue by Blananas2** [samfundev/KTANE-Bombs#58]
A "missing image" also appears next to "Avatar" using Chrome.
What causes this _could_ be someone changing their profile picture but I don't really know.

**Comment by Flamanis** [comment]
It is 99.9% likely that such an action is the cause of the issue. We were discussing what to do to avoid/fix this.

In my opinion, if a users avatar cannot be found, then we should use one of the discord default avatars in its place. Until that user logs in fresh and their avatar is retrieved through the login.
