### ISSUE TITLE
Ranking of times on bomb leaderboards.

### ISSUE THREAD

**Issue by Danielstigman** [samfundev/KTANE-Bombs#68]
Like how there is ranking for how many solves a solver has on the solvers page.

**Comment by Luminoscity** [comment]
Do you mean being able to sort missions by how many times they have been solved?
![image](https://user-images.githubusercontent.com/10985005/211975216-5352db9f-7bf1-4200-8f0e-9f9942cb4f88.png)


Or maybe the time that it takes to do a mission?
![image](https://user-images.githubusercontent.com/10985005/211975308-621f4505-24da-4488-8279-ac0fdda3fbfc.png)

**Comment by Danielstigman** [comment]
I guess I was a little too vague. What I was trying to get at is how the entries on the solvers leaderboard are numbered, and I was thinking of the same thing but for the entries on each individual bombs leaderboards.
