### ISSUE TITLE
Solos should be counted as Team Defusals with the soloer counting as a defuser.

### ISSUE THREAD

**Issue by BlvdBroken** [samfundev/KTANE-Bombs#71]
Pretty self explanitory. For example, as of right now, 5olo Bomb has only been solved as a Solo and it is listed as an EFM.
![image](https://user-images.githubusercontent.com/38589000/204190663-ae0c8794-c435-41c2-9061-c55b83bed372.png)

**Comment by Luminoscity** [comment]
Shouldn't it count only as a solo and not as a team defusal? There are 4 categories. Solo, EFM, Team, and TP

**Comment by Luminoscity** [comment]
@BlvdBroken Shouldn't it count only as a solo and not as a team defusal? There are 4 categories. Solo, EFM, Team, and TP
![image](https://user-images.githubusercontent.com/10985005/212247641-72e2c31f-cca9-4292-81f3-a3f95262dc99.png)
