### ISSUE TITLE
Upload - Do not allow users to enter the same Mission Pack, Mission, or Solve more than once

### ISSUE THREAD

**Issue by rexkix** [samfundev/KTANE-Bombs#72]
Do not allow users to enter the same Mission Pack, Mission, or Solve more than once.  
Instead, display an appropriate error message.

For Mission Packs, IDs must be unique
For Missions, name must be unique.  Or is it Name + Mission Pack?
For Solves, no two solves can share the same proof.
For Solves, if the same team is trying to register a new solve, only take it if they improve their time, then wipe out the old solve when it's verified.  (I think)

**Comment by Luminoscity** [comment]
Is done for Mission and Solve, will be done for Mission Pack in #20
