### ISSUE TITLE
Module counts for missions are sometimes incorrect.

### ISSUE THREAD

**Issue by Blananas2** [samfundev/KTANE-Bombs#84]
For example, Hotel Rwanda has 101 modules, but the site says it only has 100, both on the main page and the mission page.
There may be others but this is the first I've seen that has this issue.

**Comment by Luminoscity** [comment]
@Blananas2 can you tell me what module is missing?

**Comment by Blananas2** [comment]
There is no missing module, it's just that the count was wrong (but has since been fixed for that mission).
